M48
; DRILL file {KiCad 6.0.10+dfsg-2} date Wed 01 Feb 2023 09:38:33 AM EST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-01T09:38:33-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10+dfsg-2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X109.6Y-121.825
X109.6Y-126.825
T2
X172.0Y-85.25
T0
M30
